### ISSUE TITLE
Unable to disable directFormat within a language setting

### ISSUE THREAD

**Issue by dhananjaipai** [AkiraVoid-Productions/vscode-extension-format-with-cli#10]
First off, thank you for the extension. This was exactly what I was searching for and saves me a ton of time trying to find formatters in the wild.

Details
---
Visual Studio Code - Version: 1.91.1
Extension - v1.1.2

The issue seems to be with the extension settings

# Steps to reproduce
1. Running with directFormat false globally works
``` json
 "[just]": {
    "editor.defaultFormatter": "AkiraVoid.format-with-cli",
    "AkiraVoid.formatWithCLI.command": "just --fmt --unstable --justfile '{file}'",
  },
  "AkiraVoid.formatWithCLI.directFormat": false,
```
In the Output channel, I am getting
```log
2024-07-20 13:19:58.399 [info] Direct Format disabled.
2024-07-20 13:19:58.399 [info] Command just --fmt --unstable --justfile '<***>/justfile' executed.
```

2. Moving directFormat false inside the language block does not
``` json
 "[just]": {
    "editor.defaultFormatter": "AkiraVoid.format-with-cli",
    "AkiraVoid.formatWithCLI.command": "just --fmt --unstable --justfile '{file}'",
    "AkiraVoid.formatWithCLI.directFormat": false
  },
```
In the Output channel, I am getting
```log
2024-07-20 13:22:26.026 [info] Direct Format enabled.
2024-07-20 13:22:26.026 [info] Will run the command "just --fmt --unstable --justfile '<***>/.~format-with-cli.cache'" to format the document "<***>/justfile"
```

The problem is that the direct format does not seem to actually format the document as expected! Not sure if it is because the direct formatting is not working, or some other path based issues.

Also tested with a json file with
```
  "[json]": {
    "editor.defaultFormatter": "AkiraVoid.format-with-cli",
    "AkiraVoid.formatWithCLI.directFormat": true,
  },
  "AkiraVoid.formatWithCLI.directFormat": false,
```
It is still taking the global value and not overriding with the language-specific value.

**Comment by dhananjaipai** [comment]
Looks extremely weird, since the commands seem to be working as expected, and getting overwritten with language specific values.

```js
const getCommand = (language?: string) =>
  vscode.workspace
    .getConfiguration(
      'AkiraVoid.formatWithCLI',
      language ? { languageId: language } : undefined,
    )
    .get<string>('command', 'npx prettier --ignore-unknown "{file}"');

const isDirectFormatEnabled = (language?: string) =>
  vscode.workspace
    .getConfiguration(
      'AkiraVoid.formatWithCLI',
      language ? { languageId: language } : undefined,
    )
    .get<boolean>('directFormat', true);
```

and the source code for getting the values seem identical!

**Comment by dhananjaipai** [comment]
Ah, the issue is that when you are calling the get command function you are passing the language ID, when you are calling the isDirectFormatEnabled, you are not 
``` getCommand(doc.languageId) ```

**Comment by AkiraVoid** [comment]
Don't worry about it. It will get fixed at next release 1.1.3, and it's totally on me...

Meanwhile, you have mentioned that the Direct Format is not working for you. Could you please provide more information about this?

**Comment by dhananjaipai** [comment]
> Meanwhile, you have mentioned that the Direct Format is not working for you. Could you please provide more information about this?

It may be a gotcha with "just" formatter, let me test with JSON and get back to you.

**Comment by AkiraVoid** [comment]
OK, and the issue will be closed as soon as the pull request is merged. Just open another issue if you found that it's a problem with this extension.

**Comment by dhananjaipai** [comment]
I think the just formatter was only overwriting the original file - /.~format-with-cli.cache in this case, and not writing the output to stdout
If it writes to stdout, it will also exit with a non-zero exit code, is there a way to use direct format with the contents of the "updated" .cache file instead of the standard out?
I will try to play around with the command so that I can print it to stdout as a workaround or mask the exit code.

**Comment by AkiraVoid** [comment]
> is there a way to use direct format with the contents of the "updated" .cache file instead of the standard out?
@dhananjaipai In fact I've tested this solution but it's quite slow and is annoying for me, because it will write and read the file twice (one for the extension and one for the formatter).
